language: go

_dep_ensure: &_dep_ensure
  go: "1.11"
  before_install:
    - mkdir -p "$GOPATH/src/github.com/osrg"
    - ln -sfn "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/osrg/gobgp"
    - cd "$GOPATH/src/github.com/osrg/gobgp"
    - go get -u github.com/golang/dep/cmd/dep
  install: cd "$GOPATH/src/github.com/osrg/gobgp" && $GOPATH/bin/dep ensure

_unittest: &_unittest
  <<: *_dep_ensure
  script:
    - go test $([ $(go env GOARCH) == 'amd64' ] && echo '-race') $(go list ./... | grep -v '/vendor/') -timeout 120s
    - if [ "$(go env GOARCH)" = "amd64" ]; then go test -race github.com/osrg/gobgp/pkg/packet/bgp -run ^Test_RaceCondition$; else echo 'skip'; fi

_build: &_build
  <<: *_dep_ensure
  script:
    - go build -o ./cmd/gobgp/gobgp   ./cmd/gobgp/
    - go build -o ./cmd/gobgpd/gobgpd ./cmd/gobgpd/

matrix:
  include:
#
# Unit Tests
#
    - <<: *_unittest
      go: "1.11"
      env:
        - DESCRIPTION="Unit Tests"
    - <<: *_unittest
      go: "1.11"
      env:
        - DESCRIPTION="Unit Tests on i386"
      before_script:
        - export GOARCH="386"
        - go env
#
# Cross-compile
#
    - <<: *_build
      go: "1.11"
      env:
        - DESCRIPTION="Cross-compile openbsd"
      before_script:
        - export GOOS="openbsd"
        - go env
    - <<: *_build
      go: "1.11"
      env:
        - DESCRIPTION="Cross-compile freebsd"
      before_script:
        - export GOOS="freebsd"
        - go env
    - <<: *_build
      go: "1.11"
      env:
        - DESCRIPTION="Cross-compile darwin"
      before_script:
        - export GOOS="darwin"
        - go env

go_import_path: github.com/osrg/gobgp
